/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spacetraders;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;
import spacetraders.model.ModelFacade;
import spacetraders.model.OfflineModel;
import spacetraders.model.OnlineModel;

public class App extends Application {
    static boolean offline = false;

    ModelFacade model;

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        if(args.length < 1){
            System.out.println("Give --args=\"offline\" to switch to offline mode. \nRunning online mode by default.");
        } else {
            if(args[0].equals("offline")) {
                offline = true;
                System.out.println("Running offline version.");
            } else if (args[0].equals("online")){
                offline = false;
                System.out.println("Running online version.");
            }
        }
        //calls start()
        launch(args);
    }


    @Override
    public void start(Stage stage) throws Exception {

        Scene scene = new Scene(new Pane());

        if(offline){
            model = new OfflineModel();
        } else {
            model = new OnlineModel();
        }

        ViewSwitcher.setModel(model);
        ViewSwitcher.setScene(scene);
        ViewSwitcher.switchTo(View.LOGIN);

        stage.setScene(scene);
        stage.setTitle("Space Traders!");
        stage.show();


    }
}
